"""Data Transfer Objects (DTOs) for API requests and responses."""

from dataclasses import dataclass


@dataclass
class ChatRequestDTO:
    """DTO for chat request.
    
    Attributes:
        question: The question to answer.
    """
    question: str


@dataclass
class ChatResponseDTO:
    """DTO for chat response.
    
    Attributes:
        answer: The answer generated by LLM.
        context: The context retrieved from documents.
    """
    answer: str
    context: str
